ALTER TABLE `vlans_fdb` ADD INDEX `port_id` (`port_id`);
ALTER TABLE `wifi_sessions` ADD INDEX `device_id` (`device_id`);
ALTER TABLE `eigrp_ports` ADD INDEX `device_id` (`device_id`);
ALTER TABLE `device_graphs` ADD INDEX `graph` (`graph`);
ALTER TABLE `devices` ADD INDEX `disabled_lastpolled` (`disabled`, `last_polled_timetaken`);
ALTER TABLE `ipv4_addresses` ADD INDEX `ipv4_address` (`ipv4_address`);
ALTER TABLE `ipv6_addresses` ADD INDEX `ipv6_address` (`ipv6_address`);
ALTER TABLE `mac_accounting` ADD INDEX `device_ma` (`device_id`, `ma_id`);
ALTER TABLE `dbSchema` ADD PRIMARY KEY (`version`);
ALTER TABLE `wifi_accesspoints` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `wifi_sessions` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `dbSchema` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `alert_table-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `accesspoints-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `applications-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bgpPeers-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bgpPeers_cbgp-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `mac_accounting-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `mempools-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ports-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ports_cbqos` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `processors-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `sensors-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `storage-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ucd_diskio-state` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;