#!/bin/bash

RRDPATH=/var/lib/mailgraph

RRD_FIELDS=""
RRD_VALUES=""

for FILENAME in mailgraph_greylist.rrd mailgraph.rrd mailgraph_virus.rrd
do

  if [ -f $RRDPATH/$FILENAME ];
  then
    OUTPUT=$(rrdtool lastupdate $RRDPATH/$FILENAME 2>/dev/null)
    if [ "$OUTPUT" != "" ];
    then
      RRD_FIELDS+=$(echo "$OUTPUT"|head -n1)
      RRD_VALUES+=$(echo "$OUTPUT"|tail -n1|cut -d: -f2)
    fi
  fi
done

read -a FIELDS <<< "$RRD_FIELDS"
read -a VALUES <<< "$RRD_VALUES"

if [ ${#FIELDS[@]} != 0 ];
then
  echo "<<<postfix_mailgraph>>>"

  for i in `seq ${#FIELDS[@]}`
  do
    echo ${FIELDS[$i-1]}:${VALUES[$i-1]}
  done
fi
